Repository 7Cav/7CavAddon, pull requests merged in 2019-05, with the labels that each got.

#30 WIP: Alpha vehicles
  addons/alpha_vehicles/$PBOPREFIX$
  addons/alpha_vehicles/CfgEditorSubcategories.hpp
  addons/alpha_vehicles/CfgVehicles.hpp
  addons/alpha_vehicles/config.cpp
  addons/alpha_vehicles/script_component.hpp
  addons/alpha_vehicles/stringtable.xml
Labels: WIP, enhancement

#39 Added platoon flags
  addons/flag/CfgVehicles.hpp
  addons/flag/config.cpp
  addons/flag/data/flag_bravo2_ca.paa
  addons/flag/data/flag_charlie1_ca.paa
  addons/flag/data/flag_charlie2_ca.paa
  addons/flag/stringtable.xml
Labels: enhancement

#41 Added non team classnames
  addons/bravo_characters/CfgVehicles.hpp
  addons/bravo_characters/stringtable.xml
  addons/charlie_characters/CfgVehicles.hpp
  addons/charlie_characters/stringtable.xml
Labels: enhancement

#37 Fixed missing magazine class to weapon config
  addons/weapons/CfgWeapons.hpp
  addons/weapons/config.cpp
Labels: bugfix

#36 Added cTab fixes as optional mod
  README.md
  optionals/fix_cTab/$PBOPREFIX$
  optionals/fix_cTab/cTab.hpp
  optionals/fix_cTab/config.cpp
  optionals/fix_cTab/script_component.hpp
Labels: bugfix, enhancement

#42 Updated 2nd Platoon patch
  addons/insignia/data/Bravo_2.paa
Labels: enhancement

#43 Charlie Rifleman and CLS is replaces with Rifleman AT
  addons/charlie_characters/CfgGroups.hpp
  addons/charlie_vehicles/CfgVehicles.hpp
Labels: enhancement

#45 Added charlie officer
  addons/charlie_characters/CfgVehicles.hpp
  addons/charlie_characters/stringtable.xml
Labels: enhancement

#44 Removed havoc
  addons/charlie_characters/CfgGroups.hpp
  addons/charlie_characters/config.cpp
  addons/charlie_characters_units/CfgGroups.hpp
  addons/charlie_characters_units/config.cpp
Labels: enhancement
