Repository 7Cav/7CavAddon, pull requests merged in 2019-10, with the labels that each got.

#77 Updated validator
  tools/sqf_validator.py
Labels: ignore changelog

#75 Dynamic Objectives
  addons/dynobj/$PBOPREFIX$
  addons/dynobj/CfgEventHandlers.hpp
  addons/dynobj/XEH_PREP.hpp
  addons/dynobj/XEH_preInit.sqf
  addons/dynobj/XEH_preStart.sqf
  addons/dynobj/config.cpp
  addons/dynobj/data/infostand.paa
  addons/dynobj/data/logo.paa
  addons/dynobj/functions/fnc_aActions.sqf
  addons/dynobj/functions/fnc_aCASRange.sqf
  addons/dynobj/functions/fnc_aConditions.sqf
  addons/dynobj/functions/fnc_aMarkedLZ.sqf
  addons/dynobj/functions/fnc_bActions.sqf
  addons/dynobj/functions/fnc_cActions.sqf
  addons/dynobj/functions/fnc_cmAddAction.sqf
  addons/dynobj/functions/fnc_cmAddController.sqf
  addons/dynobj/functions/fnc_cmCleanup.sqf
  addons/dynobj/functions/fnc_cmDescFromNearLoc.sqf
  addons/dynobj/functions/fnc_cmGlobalHint.sqf
  addons/dynobj/functions/fnc_cmGridString.sqf
  addons/dynobj/functions/fnc_cmRandomName.sqf
  addons/dynobj/functions/fnc_cmRandomPosition.sqf
  addons/dynobj/functions/fnc_cmRandomVehicles.sqf
  addons/dynobj/functions/fnc_cmResetChooseDialog.sqf
  addons/dynobj/functions/fnc_cmSelectMapPos.sqf
  addons/dynobj/script_component.hpp
  addons/main/script_macros.hpp
  include/a3/data_f/$PBOPREFIX$
  include/a3/data_f/penetration/cloth.rvmat
  include/a3/data_f/penetration/default.rvmat
  include/a3/data_f/penetration/metal.rvmat
  include/a3/data_f/penetration/metal_plate.rvmat
  include/a3/data_f/penetration/metal_plate_thin.rvmat
  include/a3/data_f/penetration/plastic.rvmat
  include/a3/data_f/penetration/tyre.rvmat
  include/a3/data_f/penetration/wood.rvmat
  include/a3/ui_f/$PBOPREFIX$
  include/a3/ui_f/hpp/defineCommonColors.inc
  include/a3/ui_f/hpp/defineCommonGrids.inc
  include/a3/ui_f/hpp/defineDIKCodes.inc
  include/a3/ui_f/hpp/defineResincl.inc
  include/a3/ui_f/hpp/defineResinclDesign.inc
  include/x/cba/addons/main/$PBOPREFIX$
  include/x/cba/addons/main/script_macros_common.hpp
  include/x/cba/addons/xeh/$PBOPREFIX$
  include/x/cba/addons/xeh/script_xeh.hpp
Labels: enhancement, needs testing

#74 Fix missing F16 Tail
  addons/alpha_vehicles/CfgVehicles.hpp
Labels: bug, critical

#78 Update script_version.hpp
  addons/main/script_version.hpp
Labels: ignore changelog
