Repository 7Cav/7CavAddon, pull requests merged in 2023-07, with the labels that each got.

#200 Updated Charlie 2 3 insigna
  addons/insignia/data/Charlie_2_3.paa
Labels: enhancement

#193 Updatd charlie 2 2
  addons/insignia/data/Charlie_2_2.paa
Labels: enhancement

#194 removed gear pbo due to causing issues with build and ingame usage
  addons/gear/$PBOPREFIX$
  addons/gear/CfgVehicles.hpp
  addons/gear/CfgWeapons.hpp
  addons/gear/capb.p3d
  addons/gear/config.cpp
  addons/gear/data/BlackJumpMaster/capb_black_co.paa
  addons/gear/data/BlackJumpMaster/capb_black_ranger_co.paa
  addons/gear/data/BlackJumpMaster/capb_nohq.paa
  addons/gear/data/BlackJumpMaster/capb_ti_ca.paa
  addons/gear/data/Maroon_BeretArmyUSA/headgear_beret02.rvmat
  addons/gear/data/Maroon_BeretArmyUSA/headgear_beret02_co.paa
  addons/gear/data/Maroon_BeretArmyUSA/headgear_beret02_nohq.paa
  addons/gear/data/Maroon_BeretArmyUSA/headgear_beret02_smdi.paa
  addons/gear/data/Maroon_BeretArmyUSA/headgear_beret02_ti_ca.paa
  addons/gear/data/Maroon_BeretArmyUSA/headgear_beret03_co.paa
  addons/gear/data/RRD_Uniform/RRD_Parade.paa
  addons/gear/data/RRD_Uniform/RRD_Ribbons.paa
  addons/gear/data/UI/icon_H_Cap_blk_CA.paa
  addons/gear/data/UI/icon_h_RRDUniform.paa
  addons/gear/data/UI/icon_h_beret02_ca.paa
  addons/gear/data/UI/icon_h_stetson_ca.paa
  addons/gear/headgear_beret02.p3d
  addons/gear/script_component.hpp
  addons/gear/stringtable.xml
Labels: enhancement

#197 Removed Orbat pbo
  addons/orbat/$PBOPREFIX$
  addons/orbat/CfgOrbat.hpp
  addons/orbat/config.cpp
  addons/orbat/script_component.hpp
  addons/orbat/stringtable.xml
Labels: enhancement, cleanup

#206 Added new logo preview and banner by Jay.M
  resources/banner.jpg
  resources/logo.png
  resources/steam_preview.jpg
Labels: T-Enhancement

#204 Removed unused base class
  addons/vehicles_dragoon/CfgVehicles.hpp
Labels: T-Bugfix, needs testing

#207 Changed URL and menue now utalizes stringtable
  addons/optionsmenu/gui/mainMenu.hpp
  addons/optionsmenu/stringtable.xml
Labels: T-Enhancement
