Repository 7Cav/7CavAddon, pull requests merged in 2024-07, with the labels that each got.

#238 Updated editor config
  .editorconfig
Labels: ignore changelog, T-Tools

#241 Updated due to missing letter in name
  addons/textures/data/arlington/Arlington_Macgehee_ca.paa
Labels: T-Enhancement, ignore changelog

#243 Rewritten the readme to reflect reality
  README.md
Labels: ignore changelog

#244 Fixed dubble .paa suffix on implementation
  addons/textures/data/arlington/CfgVehicles.inc.hpp
Labels: ignore changelog, T-Bugfix

#245 Updated gitignore
  .gitignore
Labels: ignore changelog, T-Tools

#247 Fixed categories string table reference as well as arlington category not setup correctly
  addons/textures/CfgEditorSubcategories.hpp
  addons/textures/data/arlington/CfgVehicles.inc.hpp
  addons/textures/stringtable.xml
Labels: T-Enhancement

#246 Updated McGehee Arlington
  addons/textures/data/arlington/Arlington_Macgehee_ca.paa
  addons/textures/data/arlington/Arlington_Mcgehee_ca.paa
Labels: ignore changelog, T-Bugfix

#248 Added bravo company warhorse insignia
  addons/insignia/CfgUnitInsignia.hpp
  addons/insignia/data/Bravo.paa
  addons/insignia/stringtable.xml
Labels: T-Enhancement

#252 Updated Viking-1 Squad patch
  addons/insignia/data/Bravo_2_1.paa
Labels: T-Insignia

#253 Updated and fixed versioning for CBA and Arma
  .hemtt/project.toml
  addons/main/CfgSettings.hpp
  addons/main/config.cpp
  addons/main/script_mod.hpp
Labels: T-Enhancement

#250 Added leaflets and poster for public relations
  addons/leaflets/$PBOPREFIX$
  addons/leaflets/CfgLeaflets.hpp
  addons/leaflets/CfgMagazines.hpp
  addons/leaflets/CfgWeapons.hpp
  addons/leaflets/config.cpp
  addons/leaflets/script_component.hpp
  addons/leaflets/script_macros.hpp
  addons/leaflets/scripts/Cav_Leaflet_Enlist.sqf
  addons/leaflets/stringtable.xml
  addons/objects/$PBOPREFIX$
  addons/objects/CfgVehicles.hpp
  addons/objects/config.cpp
  addons/objects/data/cav_leaflets_item_enlist_today_ca.paa
  addons/objects/data/cav_poster_05_item_enlist_today_ca.paa
  addons/objects/script_component.hpp
  addons/objects/stringtable.xml
  addons/textures/data/posters/cav_enlist_today_ca.paa
Labels: T-Enhancement

#255 Updated tools and workflows
  .github/workflows/arma.yml
  .github/workflows/hemtt-deploy.yml
  .github/workflows/hemtt.yml
  addons/pronelauncher/functions/fnc_onKeyDown.sqf
  addons/pronelauncher/functions/script_component.hpp
  tools/check_strings.py
  tools/compileExtensions.py
  tools/config_style_checker.py
  tools/config_validator.py
  tools/deploy_both.ps1
  tools/deploy_legacy.ps1
  tools/extract_dependencies.py
  tools/generate_airfriction_config.py
  tools/publish.py
  tools/search_undefinedFunctions.py
  tools/setup.bat
  tools/setupEditorPreviewImages.py
  tools/sqf_linter.py
  tools/sqf_validator.py
  tools/sqfvmChecker.py
  tools/stringtable_validator.py
  tools/stringtablediag.py
  tools/updateIncludes.py
Labels: ignore changelog, T-Tools

#256 Updated tools
  .github/workflows/hemtt-deploy.yml
Labels: ignore changelog, T-Tools

#257 Updated naming of workflow
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  .github/workflows/hemtt.yml
Labels: ignore changelog, T-Tools

#258 Tools tested hard path
  .github/workflows/deploy.yml
Labels: ignore changelog, T-Tools

#259 Fixed dubble checkout
  .github/workflows/deploy.yml
Labels: ignore changelog, T-Tools

#260 Advanced deploy
  .github/workflows/deploy.yml
Labels: ignore changelog, T-Tools

#262 Advanced deploy
  .github/workflows/deploy.yml
Labels: ignore changelog, T-Tools

#263 Added tag release deploy
  .github/workflows/deploy-release.yml
  .github/workflows/deploy.yml
Labels: ignore changelog, T-Tools

#264 Fixed indent
  .github/workflows/deploy-release.yml
Labels: ignore changelog, T-Tools

#265 Updated code for tools again
  .github/workflows/deploy-release.yml
  tools/generate_airfriction_config.py
  tools/getTagVersion.ps1
Labels: ignore changelog, T-Tools

#266 Updated release more
  .github/workflows/deploy-publish.yml
  .github/workflows/deploy-release.yml
  .github/workflows/deploy.yml
  tools/deploy-getRelease.ps1
  tools/deploy-setVersion.ps1
Labels: ignore changelog, T-Tools

#268 Relase updates
  .github/workflows/deploy-publish.yml
Labels: ignore changelog, T-Tools
