Repository 7Cav/7CavAddon, pull requests merged in 2024-04, with the labels that each got.

#229 Fixed padding in macro argument
  addons/dynobj/functions/fnc_cmResetChooseDialog.sqf
  addons/mission/functions/fnc_teleport.sqf
Labels: cleanup

#227 Updated B/1/A/1-7 insignia
  addons/insignia/data/Alpha_1_B.paa
Labels: T-Insignia

#230 Fixed mod description strings as well as removed RHSAFRF
  addons/main/config.cpp
  addons/main/stringtable.xml
Labels: cleanup

#231 Added check for using hemtt
  .github/workflows/arma.yml
Labels: ignore changelog, T-Tools

#224 Added HEI to stryker dragoon autocannon
  addons/vehicles_dragoon/CfgAmmo.hpp
  addons/vehicles_dragoon/CfgMagazines.hpp
  addons/vehicles_dragoon/CfgVehicles.hpp
  addons/vehicles_dragoon/CfgWeapons.hpp
  addons/vehicles_dragoon/config.cpp
  addons/vehicles_dragoon/stringtable.xml
Labels: T-Enhancement

#235 Updated build script to use hemtt.launch.default instead hemtt.launch
  .hemtt/project.toml
Labels: ignore changelog, T-Tools

#232 Removed extra smoke magazine
  addons/vehicles_dragoon/CfgVehicles.hpp
Labels: T-Bugfix

#233 Cleaned and updated the insignia module
  addons/insignia/CfgUnitInsignia.hpp
  addons/insignia/script_component.hpp
  addons/insignia/script_macros.hpp
  addons/insignia/stringtable.xml
Labels: cleanup

#234 Added predefined cav respawn templates
  addons/respawn/$PBOPREFIX$
  addons/respawn/CfgRespawnTemplates.hpp
  addons/respawn/config.cpp
  addons/respawn/script_component.hpp
  addons/respawn/stringtable.xml
Labels: T-Enhancement, needs testing
